environment:

  matrix:

    - MINICONDA: C:\Miniconda35

init:
- "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda install pip numpy
  - conda install -c conda-forge pypandoc
  - "pip install -q pytest"
  - "pip install -q pypandoc"
  - "pip install -qr requirements.txt"
  - "pip install ."
  - "echo done"

build: false

test_script:
  - "python -m pytest -s -v multimatch_gaze/tests"


